import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $=id=>document.getElementById(id), host=$('scene');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x071019,.012);
const camera=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,.1,500);camera.position.set(44,25,42);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);controls.maxDistance=130;controls.minDistance=12;
scene.add(new THREE.HemisphereLight(0xbfe8ff,0x1b0b04,2));const key=new THREE.DirectionalLight(0xffffff,4.2);key.position.set(22,30,24);scene.add(key);const rim=new THREE.PointLight(0x48cfff,70,70);rim.position.set(-28,12,-20);scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(180,100),new THREE.MeshStandardMaterial({color:0x09131b,roughness:.9,metalness:.1}));floor.rotation.x=-Math.PI/2;floor.position.y=-6.3;scene.add(floor);const grid=new THREE.GridHelper(140,70,0x274256,0x162836);grid.position.y=-6.2;scene.add(grid);

const kilnGroup=new THREE.Group();kilnGroup.rotation.z=-.025;scene.add(kilnGroup);const shellGroup=new THREE.Group(),bedGroup=new THREE.Group(),cellGrid=new THREE.Group();kilnGroup.add(shellGroup,bedGroup,cellGrid);
const N=48,L=72,cellLen=L/N,segmentMeshes=[],bedMeshes=[],edgeMeshes=[];const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function tempColor(t){const u=clamp((t-300)/900,0,1),c=new THREE.Color();if(u<.33)c.lerpColors(new THREE.Color(0x2744c7),new THREE.Color(0x20d2c8),u/.33);else if(u<.66)c.lerpColors(new THREE.Color(0x20d2c8),new THREE.Color(0xffe56c),(u-.33)/.33);else c.lerpColors(new THREE.Color(0xffe56c),new THREE.Color(0xd72b47),(u-.66)/.34);return c}
function profile(p){const a=[];for(let i=0;i<N;i++){const x=i/(N-1),pre=1/(1+Math.exp(-(x-.28)*10)),burn=Math.exp(-Math.pow((x-.72)/.20,2)),base=360+510*pre+235*burn,fuel=(p.fuel-100)*3.2*(.25+.75*burn),feed=-(p.feed-100)*1.55*(.3+.7*pre),speed=(p.speed-2)*-30*(.2+.8*pre),bed=clamp(base+fuel+feed+speed,300,1198),wall=clamp(bed+80+60*burn,350,1198),conv=clamp((bed-760)/390,0,1)*clamp((x-.22)/.55,0,1);a.push({x:i*cellLen,bed,wall,conv})}return a}
for(let i=0;i<N;i++){const geo=new THREE.CylinderGeometry(5,5,cellLen*.96,44,1,true);geo.rotateZ(Math.PI/2);const mat=new THREE.MeshStandardMaterial({color:0x567180,roughness:.52,metalness:.54,transparent:true,opacity:.72,side:THREE.DoubleSide}),m=new THREE.Mesh(geo,mat);m.position.x=-L/2+cellLen*(i+.5);m.userData.cell=i;shellGroup.add(m);segmentMeshes.push(m);const bg=new THREE.BoxGeometry(cellLen*.88,1,6.7),bm=new THREE.MeshStandardMaterial({color:0xb98b52,roughness:.95}),b=new THREE.Mesh(bg,bm);b.position.set(m.position.x,-2.8,0);b.userData.cell=i;bedGroup.add(b);bedMeshes.push(b);const e=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(cellLen*.98,10.2,10.2)),new THREE.LineBasicMaterial({color:0x5dd7ff,transparent:true,opacity:.16}));e.position.x=m.position.x;e.visible=false;cellGrid.add(e);edgeMeshes.push(e)}
function tower(x,h,w=7){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(w,h,w),new THREE.MeshStandardMaterial({color:0x25343e,roughness:.65,metalness:.5}));body.position.y=h/2-6;g.add(body);const pipe=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.2,7,20),new THREE.MeshStandardMaterial({color:0x415768,metalness:.6,roughness:.45}));pipe.position.y=h-3;g.add(pipe);g.position.x=x;g.position.z=-14;scene.add(g)}tower(-43,25);tower(-33,20,6);tower(44,13,10);
const ring=new THREE.Mesh(new THREE.TorusGeometry(5.25,.09,8,64),new THREE.MeshBasicMaterial({color:0xffffff}));ring.rotation.y=Math.PI/2;kilnGroup.add(ring);
const p={fuel:100,feed:100,speed:2,selected:0};let data=profile(p);
function selectCell(i,slider=true){p.selected=clamp(Number(i)||0,0,N-1);if(slider)$('axial').value=p.selected;$('axialOut').textContent=p.selected;$('cellNo').textContent=String(p.selected+1).padStart(2,'0');const d=data[p.selected];ring.position.x=-L/2+cellLen*(p.selected+.5);$('detailX').textContent=d.x.toFixed(1)+' m';$('detailBed').textContent=d.bed.toFixed(0)+' K';$('detailWall').textContent=d.wall.toFixed(0)+' K';$('detailConv').textContent=(d.conv*100).toFixed(1)+' %'}
function draw(){const c=$('profile'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#071019';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1c3343';ctx.lineWidth=1;for(let j=0;j<5;j++){const y=18+j*(h-36)/4;ctx.beginPath();ctx.moveTo(38,y);ctx.lineTo(w-10,y);ctx.stroke()}const tx=i=>38+i*(w-52)/(N-1),ty=t=>h-18-(t-300)/900*(h-36);ctx.strokeStyle='#62d4ff';ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>i?ctx.lineTo(tx(i),ty(d.bed)):ctx.moveTo(tx(i),ty(d.bed)));ctx.stroke();ctx.strokeStyle='#ff9d5c';ctx.lineWidth=2;ctx.beginPath();data.forEach((d,i)=>i?ctx.lineTo(tx(i),ty(d.wall)):ctx.moveTo(tx(i),ty(d.wall)));ctx.stroke();const sx=tx(p.selected);ctx.strokeStyle='#fff';ctx.globalAlpha=.65;ctx.beginPath();ctx.moveTo(sx,10);ctx.lineTo(sx,h-12);ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle='#8da3b5';ctx.font='20px system-ui';ctx.fillText('Bed T',46,31);ctx.fillStyle='#ffb186';ctx.fillText('Wall T',135,31)}
function refresh(){data=profile(p);data.forEach((d,i)=>{segmentMeshes[i].material.color.copy(tempColor(d.wall));bedMeshes[i].material.color.copy(tempColor(d.bed));bedMeshes[i].scale.y=.75+.65*d.conv});$('peakT').textContent=Math.max(...data.map(d=>d.bed)).toFixed(0);$('conversion').textContent=(data.at(-1).conv*100).toFixed(1);$('energy').textContent=(100*(p.fuel/100)*(100/p.feed)*(2/p.speed)).toFixed(1);selectCell(p.selected,false);draw()}
for(const id of ['fuel','feed','speed']){const el=$(id),out=$(id+'Out');el.addEventListener('input',()=>{p[id]=Number(el.value);out.textContent=el.value;refresh()})}$('axial').addEventListener('input',()=>selectCell(Number($('axial').value),false));
document.querySelectorAll('.layer').forEach(btn=>btn.addEventListener('click',()=>{btn.classList.toggle('active');const on=btn.classList.contains('active'),name=btn.dataset.layer;if(name==='shell')shellGroup.visible=on;if(name==='bed')bedGroup.visible=on;if(name==='grid')edgeMeshes.forEach(x=>x.visible=on);if(name==='thermal')segmentMeshes.forEach(x=>x.material.opacity=on?.72:.22)}));
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',ev=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects([...segmentMeshes,...bedMeshes],false)[0];if(hit)selectCell(hit.object.userData.cell)});
const views={overview:{p:[44,25,42],t:[0,0,0]},preheat:{p:[-43,12,24],t:[-27,0,0]},burning:{p:[20,10,23],t:[18,0,0]},cooler:{p:[47,9,20],t:[34,0,0]}};let fly=null;function flyTo(v){const x=views[v];fly={start:performance.now(),fromP:camera.position.clone(),fromT:controls.target.clone(),toP:new THREE.Vector3(...x.p),toT:new THREE.Vector3(...x.t)}}document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>flyTo(b.dataset.view)));$('resetView').addEventListener('click',()=>flyTo('overview'));
function animate(now){requestAnimationFrame(animate);if(fly){const u=clamp((now-fly.start)/900,0,1),e=1-Math.pow(1-u,3);camera.position.lerpVectors(fly.fromP,fly.toP,e);controls.target.lerpVectors(fly.fromT,fly.toT,e);if(u>=1)fly=null}kilnGroup.rotation.x=Math.sin(now*.00018)*.003;controls.update();renderer.render(scene,camera)}refresh();requestAnimationFrame(animate);
new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe(host);window.addEventListener('keydown',e=>{if(e.key==='1')flyTo('overview');if(e.key==='2')flyTo('preheat');if(e.key==='3')flyTo('burning');if(e.key==='4')flyTo('cooler')});
